/** Unmodified AWS Architecture Icons. See public/aws-icons/ATTRIBUTION.md. */
export const serviceIcons: Record<string, string> = {
  s3: 's3.svg',
  glacier: 'glacier.svg',
  lakeformation: 'lakeformation.svg',
  glue: 'glue.svg',
  dms: 'dms.svg',
  datasync: 'datasync.svg',
  athena: 'athena.svg',
  redshift: 'redshift.svg',
  emr: 'emr.svg',
  opensearch: 'opensearch.svg',
  kinesis: 'kinesis.svg',
  firehose: 'firehose.svg',
  msk: 'msk.svg',
  sqs: 'sqs.svg',
  sns: 'sns.svg',
  eventbridge: 'eventbridge.svg',
  rds: 'rds.svg',
  aurora: 'aurora.svg',
  dynamodb: 'dynamodb.svg',
  lambda: 'lambda.svg',
  stepfunctions: 'stepfunctions.svg',
  mwaa: 'mwaa.svg',
  cloudwatch: 'cloudwatch.svg',
  cloudtrail: 'cloudtrail.svg',
  iam: 'iam.svg',
  kms: 'kms.svg',
  secrets: 'secrets.svg',
  macie: 'macie.svg',
  flink: 'flink.svg',
  catalog: 'catalog.svg',
  crawler: 'crawler.svg',
  quality: 'quality.svg',
  efs: 'efs.svg',
  eks: 'eks.svg',
  appflow: 'appflow.svg',
  scheduler: 'scheduler.svg',
  parameterstore: 'parameterstore.svg',
  ec2: 'ec2.svg',
  vpc: 'vpc.svg',
  route53: 'route53.svg',
  cloudfront: 'cloudfront.svg',
  elb: 'elb.svg',
};

const aliases: Record<string, string> = {
  simplestorageservice: 's3',
  simplestorageserviceglacier: 'glacier',
  s3glacier: 'glacier',
  s3bucket: 's3',
  lambdafunction: 'lambda',
  ec2instance: 'ec2',
  dynamodbtable: 'dynamodb',
  sqsqueue: 'sqs',
  snstopic: 'sns',
  stepfunctionsstatemachine: 'stepfunctions',
  gluemetastore: 'catalog',
  gluedatacatalog: 'catalog',
  datacatalog: 'catalog',
  gluecrawler: 'crawler',
  gluedataquality: 'quality',
  glueetl: 'glue',
  databasemigrationservice: 'dms',
  redshiftspectrum: 'redshift',
  redshiftserverless: 'redshift',
  opensearchservice: 'opensearch',
  kinesisdatastreams: 'kinesis',
  datastreams: 'kinesis',
  kinesisdatafirehose: 'firehose',
  datafirehose: 'firehose',
  managedstreamingforapachekafka: 'msk',
  simplequeueservice: 'sqs',
  simplenotificationservice: 'sns',
  managedworkflowsforapacheairflow: 'mwaa',
  identityandaccessmanagement: 'iam',
  keymanagementservice: 'kms',
  secretsmanager: 'secrets',
  managedserviceforapacheflink: 'flink',
  kinesisdataanalytics: 'flink',
  elastickubernetesservice: 'eks',
  eventbridgescheduler: 'scheduler',
  systemsmanagerparameterstore: 'parameterstore',
  elasticcomputecloud: 'ec2',
  virtualprivatecloud: 'vpc',
  elasticloadbalancing: 'elb',
  applicationloadbalancer: 'elb',
  networkloadbalancer: 'elb',
  alb: 'elb',
  nlb: 'elb',
};

export function iconFileFor(service: string | null): string | null {
  if (!service) return null;
  const normalized = service
    .toLowerCase()
    .trim()
    .replace(/^(?:amazon|aws)[\s_-]*/, '')
    .replace(/[^a-z0-9]/g, '');
  const key = aliases[normalized] ?? normalized;
  return Object.hasOwn(serviceIcons, key) ? serviceIcons[key]! : null;
}
